name: calipay
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  smooth_page_indicator: ^1.1.0
  eva_icons_flutter: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway.ttf

    - family: Raleway-Light
      fonts:
        - asset: fonts/Raleway-Light.ttf

    - family: Poppins-Regular
      fonts:
        - asset: fonts/Poppins-Regular.ttf

    - family: Poppins-Bold
      fonts:
        - asset: fonts/Poppins-Bold.ttf

    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: fonts/Nunito-Bold.ttf
          weight: 700





  assets:
    - assets/
    - assets/calipay_logo.png
    - assets/logo_filled.png
    - assets/colored_background.png
    - assets/customers.png
    - assets/suppliers.png
    - assets/products.png
    - assets/pos.png
    - assets/orders.png
    - assets/expenses.png
    - assets/report.png
    - assets/settings.png
    - assets/profile.png
    - assets/sales.png
    - assets/mouse.png
    - assets/cart.png
    - assets/tv.png
    - assets/expense_icon.png

